"""
Optional Gemini LLM integration for text synthesis.

This module wraps the ``google-genai`` SDK.  If that package is not installed
the helpers in this module still import cleanly; they will raise an
:class:`ImportError` with a helpful message when called.

Install the optional dependency with::

    pip install looker_powerpoint[llm]

and set the ``GOOGLE_API_KEY`` (or ``GEMINI_API_KEY``) environment variable
before using any function in this module.
"""

import logging
import os

try:
    from google import genai  # type: ignore[import]

    _HAS_GEMINI = True
except ImportError:  # pragma: no cover
    _HAS_GEMINI = False


def is_available() -> bool:
    """Return ``True`` if the ``google-genai`` package is installed."""
    return _HAS_GEMINI


def synthesize(
    prompt: str | None,
    context_data_str: str,
    current_text: str,
    model_name: str = "gemini-2.0-flash",
) -> str:
    """
    Call the Gemini API and return the synthesized text.

    Parameters
    ----------
    prompt:
        An optional user-supplied instruction or question that guides the model.
    context_data_str:
        Pre-assembled context string built from the shape's ``contexts`` list.
        May include Looker data, slide text, prior Gemini results, or the
        shape's own current text — depending on what the user configured.
        Each section is separated by a blank line and prefixed with a label.
    current_text:
        The current text content of the PowerPoint shape.  Always passed so the
        model knows it is producing a replacement for existing slide text.
    model_name:
        Gemini model identifier, e.g. ``"gemini-2.0-flash"``.

    Returns
    -------
    str
        The text generated by Gemini.

    Raises
    ------
    ImportError
        If ``google-genai`` is not installed.
    ValueError
        If no API key is configured.
    """
    if not _HAS_GEMINI:
        raise ImportError(
            "google-genai is not installed. "
            "Install it with 'pip install looker_powerpoint[llm]' to use LLM features."
        )

    api_key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise ValueError(
            "Neither GOOGLE_API_KEY nor GEMINI_API_KEY environment variable is set. "
            "Set one of them to enable Gemini synthesis."
        )

    client = genai.Client(api_key=api_key)

    parts: list[str] = []

    if context_data_str:
        parts.append(f"Context:\n{context_data_str}")

    if current_text:
        parts.append(f"Current text in the shape:\n{current_text}")

    if prompt:
        parts.append(f"Instructions:\n{prompt}")

    parts.append(
        "Please provide a concise text response that will replace the current text "
        "in a PowerPoint slide. Return only the replacement text, without any "
        "additional commentary or markdown formatting."
    )

    full_prompt = "\n\n".join(parts)
    logging.debug("Gemini prompt (truncated): %s", full_prompt[:200])

    response = client.models.generate_content(
        model=model_name,
        contents=full_prompt,
    )
    return response.text
