name: Deploy Release

on:
  release:
    types: [published]


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        publish: false

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}

    - name: Build
      run: |
        uv build

    - name: Publish
      env:
        token: ${{ secrets.PYPI_TOKEN }}
      run: |
        uv publish --token $token
